[package]
name = "curfb_electrochem_model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.95"
rayon = "1.7.0"
rand = "0.8.5"
csv = "1.1"